"""create alpha entities and auth

Revision ID: 20260824_0002
Revises: 20260824_0001
Create Date: 2026-08-24 13:09:28.189788
"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260824_0002"
down_revision: str | None = "20260824_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ENUM_TYPE_NAMES = (
    "radar_type",
    "resource_status",
    "source_type",
    "collection_trigger_type",
    "collection_run_status",
    "raw_item_status",
    "document_status",
    "analysis_status",
    "recommendation",
    "notification_priority",
    "notification_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column(
            "profile",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_users_active_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "radars",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column(
            "radar_type",
            sa.Enum(
                "academic",
                "business",
                "technology",
                "market",
                "policy",
                "competitive",
                "custom",
                name="radar_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "categories",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "keywords",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "paused", "archived", name="resource_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("notification_threshold", sa.SmallInteger(), server_default="75", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "notification_threshold BETWEEN 0 AND 100", name="radars_notification_threshold_check"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_radars_user_id"), "radars", ["user_id"], unique=False)
    op.create_index(
        "uq_radars_active_user_name",
        "radars",
        ["user_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_token_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_token_id"], ["refresh_tokens.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_replaced_by_token_id"),
        "refresh_tokens",
        ["replaced_by_token_id"],
        unique=False,
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("source_type", sa.Enum("rss", "url", "api", name="source_type"), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("normalized_url", sa.Text(), nullable=False),
        sa.Column("poll_interval_minutes", sa.Integer(), server_default="60", nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "paused", "archived", name="resource_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_fetch_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "poll_interval_minutes >= 15", name="sources_poll_interval_minutes_check"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sources_status_next_fetch_at", "sources", ["status", "next_fetch_at"], unique=False
    )
    op.create_index(op.f("ix_sources_user_id"), "sources", ["user_id"], unique=False)
    op.create_index(
        "uq_sources_active_user_url",
        "sources",
        ["user_id", "normalized_url"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "collection_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("triggered_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "trigger_type",
            sa.Enum("schedule", "manual", name="collection_trigger_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued", "running", "succeeded", "partial", "failed", name="collection_run_status"
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duplicate_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fetched_count >= 0 AND created_count >= 0 AND duplicate_count >= 0 AND failed_count >= 0",
            name="collection_runs_check",
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["triggered_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_collection_runs_source_created_at",
        "collection_runs",
        ["source_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_runs_source_id"), "collection_runs", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_collection_runs_triggered_by_user_id"),
        "collection_runs",
        ["triggered_by_user_id"],
        unique=False,
    )
    op.create_index(
        "uq_collection_runs_source_idempotency",
        "collection_runs",
        ["source_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "radar_sources",
        sa.Column("radar_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["radar_id"], ["radars.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("radar_id", "source_id"),
    )
    op.create_index(
        op.f("ix_radar_sources_source_id"),
        "radar_sources",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "raw_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("collection_run_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=512), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_type", sa.String(length=160), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("fetched", "cleaned", "duplicate", "failed", name="raw_item_status"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["collection_run_id"], ["collection_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_items_collection_run_id"), "raw_items", ["collection_run_id"], unique=False
    )
    op.create_index("ix_raw_items_content_hash", "raw_items", ["content_hash"], unique=False)
    op.create_index(op.f("ix_raw_items_source_id"), "raw_items", ["source_id"], unique=False)
    op.create_index(
        "uq_raw_items_source_external",
        "raw_items",
        ["source_id", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_item_id", sa.UUID(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=300), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "cleaning",
                "deduplicating",
                "analyzing",
                "embedding",
                "ready",
                "failed",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("word_count >= 0", name="documents_word_count_check"),
        sa.ForeignKeyConstraint(["raw_item_id"], ["raw_items.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index(op.f("ix_documents_raw_item_id"), "documents", ["raw_item_id"], unique=True)
    op.create_index(
        "ix_documents_status_created_at", "documents", ["status", "created_at"], unique=False
    )
    op.create_table(
        "analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("radar_id", sa.UUID(), nullable=False),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("relevance", sa.SmallInteger(), nullable=True),
        sa.Column("importance", sa.SmallInteger(), nullable=True),
        sa.Column("novelty", sa.SmallInteger(), nullable=True),
        sa.Column("impact", sa.SmallInteger(), nullable=True),
        sa.Column("radar_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "recommendation",
            sa.Enum("must_read", "read", "monitor", "archive", name="recommendation"),
            nullable=True,
        ),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=True),
        sa.Column("model", sa.String(length=160), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "completed", "failed", name="analysis_status"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(relevance BETWEEN 0 AND 100 OR relevance IS NULL) AND (importance BETWEEN 0 AND 100 OR importance IS NULL) AND (novelty BETWEEN 0 AND 100 OR novelty IS NULL) AND (impact BETWEEN 0 AND 100 OR impact IS NULL) AND (radar_score BETWEEN 0 AND 100 OR radar_score IS NULL)",
            name="analyses_check",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["radar_id"], ["radars.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "radar_id", "pipeline_version"),
    )
    op.create_index(op.f("ix_analyses_document_id"), "analyses", ["document_id"], unique=False)
    op.create_index(op.f("ix_analyses_radar_id"), "analyses", ["radar_id"], unique=False)
    op.create_index(
        "ix_analyses_radar_status_created_at",
        "analyses",
        ["radar_id", "status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "bookmarks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "document_id"),
    )
    op.create_index(op.f("ix_bookmarks_document_id"), "bookmarks", ["document_id"], unique=False)
    op.create_index(op.f("ix_bookmarks_user_id"), "bookmarks", ["user_id"], unique=False)
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(dim=1536), nullable=False),
        sa.Column("embedding_model", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("chunk_index >= 0", name="document_chunks_chunk_index_check"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", "embedding_model"),
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_table(
        "ai_usage_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.UUID(), nullable=True),
        sa.Column("task_type", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "estimated_cost", sa.Numeric(precision=12, scale=6), server_default="0", nullable=False
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0 AND total_tokens >= 0 AND estimated_cost >= 0 AND duration_ms >= 0",
            name="ai_usage_records_check",
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_usage_records_analysis_id"), "ai_usage_records", ["analysis_id"], unique=False
    )
    op.create_index(
        "ix_ai_usage_records_user_created_at",
        "ai_usage_records",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_records_user_id"), "ai_usage_records", ["user_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("normal", "high", "critical", name="notification_priority"),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("unread", "read", name="notification_status"),
            server_default="unread",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "analysis_id"),
    )
    op.create_index(
        op.f("ix_notifications_analysis_id"), "notifications", ["analysis_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_index(
        "ix_notifications_user_status_created_at",
        "notifications",
        ["user_id", "status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_user_status_created_at", table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_analysis_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_ai_usage_records_user_id"), table_name="ai_usage_records")
    op.drop_index("ix_ai_usage_records_user_created_at", table_name="ai_usage_records")
    op.drop_index(op.f("ix_ai_usage_records_analysis_id"), table_name="ai_usage_records")
    op.drop_table("ai_usage_records")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_bookmarks_user_id"), table_name="bookmarks")
    op.drop_index(op.f("ix_bookmarks_document_id"), table_name="bookmarks")
    op.drop_table("bookmarks")
    op.drop_index("ix_analyses_radar_status_created_at", table_name="analyses")
    op.drop_index(op.f("ix_analyses_radar_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_document_id"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_index("ix_documents_status_created_at", table_name="documents")
    op.drop_index(op.f("ix_documents_raw_item_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(
        "uq_raw_items_source_external",
        table_name="raw_items",
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_raw_items_source_id"), table_name="raw_items")
    op.drop_index("ix_raw_items_content_hash", table_name="raw_items")
    op.drop_index(op.f("ix_raw_items_collection_run_id"), table_name="raw_items")
    op.drop_table("raw_items")
    op.drop_index(op.f("ix_radar_sources_source_id"), table_name="radar_sources")
    op.drop_table("radar_sources")
    op.drop_index(
        "uq_collection_runs_source_idempotency",
        table_name="collection_runs",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index(op.f("ix_collection_runs_triggered_by_user_id"), table_name="collection_runs")
    op.drop_index(op.f("ix_collection_runs_source_id"), table_name="collection_runs")
    op.drop_index("ix_collection_runs_source_created_at", table_name="collection_runs")
    op.drop_table("collection_runs")
    op.drop_index(
        "uq_sources_active_user_url",
        table_name="sources",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_sources_user_id"), table_name="sources")
    op.drop_index("ix_sources_status_next_fetch_at", table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_replaced_by_token_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        "uq_radars_active_user_name",
        table_name="radars",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_radars_user_id"), table_name="radars")
    op.drop_table("radars")
    op.drop_index(
        "uq_users_active_email", table_name="users", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_table("users")
    for enum_name in reversed(ENUM_TYPE_NAMES):
        op.execute(sa.text(f'DROP TYPE "{enum_name}"'))

    # ### end Alembic commands ###
